### ISSUE TITLE
Create new states instead of updating

### ISSUE THREAD

**Issue by lambdaofgod** [ash-project/ash_state_machine#11]
I am trying to use the state machine in a setting where I want to persist every transition so that I can use `Ash.Query` to retrieve the transition history. How to approach this? I wrote some code that tries to add this functionality, but I've run in some problems.

### Proposed approach

The default behavior uses changesets that update the states, so I wrote something like this in `change after_transaction` (`to_attributes_map` gets the attributes I'm passing to next state)

```
fn changeset, {:ok, result} ->
    State
    |> Ash.Changeset.for_create(:create, result |> to_attributes_map())
    |> Ash.Changeset.force_change_attribute(:state, changeset.attributes[:state])
    |> State.Api.create()
```

The problem is this way when I query
- I don't see the state that comes from `State.create!`
- the last state is duplicated

### Questions

Is there a more straightforward approach? Is there something obviously wrong with my approach that results in the mentioned problems?

Thanks in advance!

**Comment by zachdaniel** [comment]
Interesting... I'll have to consider how you might do this. It's a reasonable thing to want to do, but the current implementation assumes you're updating each state machine record. This isn't released on hex yet but I'm curious how you feel about something like this: https://github.com/ash-project/ash_paper_trail to track state transitions, as opposed to doing it via creating new records of your state machine resource each time

**Comment by lambdaofgod** [comment]
Looks great. Did you by any chance try this with state machines? If not, can you describe what would be required to wire this with `ash_state_machine`?  Is it as simple as using `PaperTrail.action!` instead of `Resource.action!`?

I'd be willing to contribute a guide once I'll get the hang of it but currently it doesn't seem obvious to me how to use `PaperTrail` with transition actions.

**Comment by zachdaniel** [comment]
Hey @lambdaofgod, ash_paper_trail is still *slightly* formative, although it's solidifying. I definitely think some guides would be great. @rgraff has been pushing the development forward, and it's likely in a good place now to try out. I like the idea of having something in this repo like "using with FSMs", assuming that there are any special considerations. And documentation help is *always* welcomed. In the case of `ash_paper_trail`, I'd suggest checking with @rgraff on details.

**Comment by lambdaofgod** [comment]
Ok I tried paper trail and it looks really promising, but I have one question - how do I run queries using state attributes?

I have something that works for querying `State` like this

```
State
  |> Ash.Query.filter(field_name == ^field_value)
  |> State.Api.read!()
```

How to translate it to a query on `State.Version` so that I can effectively get changesets that were applied to the selected `State`s?

**Comment by zachdaniel** [comment]
If you use `attributes_as_attributes [:state]`, it will expose the `state` as a proper attribute on the version resource, then you can do things like:
```elixir
VersionResource
|> Ash.Query.filter(state == ^state)
```

**Comment by rgraff** [comment]
Or do you want a flag on the version where a state change?

**Comment by lambdaofgod** [comment]
Ok, makes sense. I though that `:state` is some kind of special attribute.

@zachdaniel on another topic, since in my use case debugging state machine runs is extremely important, I've written utils for visualizing actual runs of a state machine, for example see [this livebook](https://github.com/lambdaofgod/livebooks/blob/master/ash_fsm.livemd). For an example FSM that looks like 

![image](https://github.com/ash-project/ash_state_machine/assets/3647577/788465aa-a83a-4571-a125-22fa74497cd9)

Example run can be viewed as

![image](https://github.com/ash-project/ash_state_machine/assets/3647577/a7e3d888-7717-4b39-8d6d-55b6240abc64)

 What do you think about adding this to `ash_state_machine`? Where would I put this module?

**Comment by zachdaniel** [comment]
That looks *sick*. How is it implemented?

**Comment by zachdaniel** [comment]
oh, I see from the live book. This is pretty awesome. I *think* it should go in `ash_paper_trail`. I want this for my own stuff so lets definitely get this in :)
