### ISSUE TITLE
Make `transition_state` atomic

### ISSUE THREAD

**Issue by linusdm** [ash-project/ash_state_machine#16]
Currently, adding [transition_state](https://hexdocs.pm/ash_state_machine/AshStateMachine.BuiltinChanges.html#transition_state/1) to an action results in a compile error when the action is not defined as `require_atomic?: false`.

I think it should be possible to add this change, without forgoing atomicity.

ash: v3.0
ash_state_machine: v0.2.2

**Comment by zachdaniel** [comment]
If you are using `ash_postgres`, make sure that you have `"ash-functions"` in your list of installed extensions.

**Comment by zachdaniel** [comment]
Just pushed up this feature, just keep in mind that it only works in that context (something I need to make much more clear)

**Comment by zachdaniel** [comment]
I've just made it a part of the getting started guide for ash_postgres

**Comment by zachdaniel** [comment]
There are also some nice changes in `ash` `main` branch that simplify the actual produced query by better eager evaluation.

**Comment by linusdm** [comment]
Thinking about this, makes me realise this is quite amazing. I would have never taken the time to make such an action atomic with just ecto. I maybe would have locked somehow, if it were very important. But now it's just a drop-in-don't-think-about-it feature... cool! 🚀
